global:
  scrape_interval: 3s

scrape_configs:
  - job_name: 'api_gateway'
    static_configs:
      - targets: [ 'learn_anything_service:8000' ]
  - job_name: 'course_platform'
    static_configs:
      - targets: [ 'learn_anything_service:8001' ]
